# Generated by Django 5.0.6 on 2024-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=255, verbose_name='Kichik Sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('button_text', models.CharField(max_length=100, verbose_name='Tugma Matni')),
                ('button_link', models.URLField(verbose_name='Tugma Havolasi')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Rasm')),
                ('image_alt', models.CharField(max_length=255, verbose_name='Rasm Tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
            },
        ),
    ]
