# Generated by Django 5.0.6 on 2024-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='target',
            field=models.BooleanField(default=False, verbose_name='Yangi oynada ochilsinmi?'),
        ),
    ]
