# Generated by Django 5.0.6 on 2024-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_slider_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Sanoq')),
                ('count_title', models.CharField(max_length=255, verbose_name='Sanoq Sarlavhasi')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Rasm')),
                ('alt', models.CharField(max_length=255, verbose_name='Rasm Tavsifi')),
                ('cap_title', models.CharField(max_length=255, verbose_name='Kichik Sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('title_1', models.CharField(max_length=255, verbose_name='1 - Qulaylik')),
                ('body_1', models.CharField(max_length=255, verbose_name='1 - Qulaylik matni')),
                ('title_2', models.CharField(max_length=255, verbose_name='1 - Qulaylik')),
                ('body_2', models.CharField(max_length=255, verbose_name='1 - Qulaylik matni')),
                ('two_body', models.TextField(verbose_name='Ikkinchi Matn')),
                ('quote', models.CharField(max_length=255, verbose_name='Iqtibos')),
            ],
            options={
                'verbose_name': 'Biz Haqimizda',
                'verbose_name_plural': 'Biz Haqimizdalar',
            },
        ),
    ]
