# Generated by Django 5.0.6 on 2024-07-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_homeabout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': '2. Biz Haqimizda', 'verbose_name_plural': '2. Biz Haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': '1. Slayder', 'verbose_name_plural': '1. Slayderlar'},
        ),
    ]
