# Generated by Django 5.0.6 on 2024-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_homeabout_options_alter_slider_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_cap', models.CharField(max_length=255, verbose_name='Yangiliklar kichik sarlavhasi')),
                ('news_title', models.CharField(max_length=255, verbose_name='Yangiliklar sarlavhasi')),
                ('courses_cap', models.CharField(max_length=255, verbose_name='Kurslar kichik sarlavhasi')),
                ('courses_title', models.CharField(max_length=255, verbose_name='Kurslar sarlavhasi')),
                ('news2_cap', models.CharField(max_length=255, verbose_name='Ikkinchi yangiliklar kichik sarlavhasi')),
                ('news2_title', models.CharField(max_length=255, verbose_name='Ikkinchi yangiliklar sarlavhasi')),
                ('liders_cap', models.CharField(max_length=255, verbose_name='Liderlar kichik sarlavhasi')),
                ('liders_title', models.CharField(max_length=255, verbose_name='Liderlar sarlavhasi')),
                ('faq_cap', models.CharField(max_length=255, verbose_name='FAQ kichik sarlavhasi')),
                ('faq_title', models.CharField(max_length=255, verbose_name='FAQ sarlavhasi')),
                ('partners_cap', models.CharField(max_length=255, verbose_name='Hamkorlar kichik sarlavhasi')),
                ('partners_title', models.CharField(max_length=255, verbose_name='Hamkorlar sarlavhasi')),
            ],
            options={
                'verbose_name': 'Uy sahifa sarlavhalari',
                'verbose_name_plural': 'Uy sahifa sarlavhalari',
            },
        ),
    ]
