# Generated by Django 5.0.6 on 2024-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_hometitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=255, verbose_name='Kichik Sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Kurslar',
                'verbose_name_plural': 'Kurslar',
            },
        ),
    ]
