# Generated by Django 5.0.6 on 2024-07-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_homecourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecourses',
            options={'verbose_name': "3. Yo'nalishlar", 'verbose_name_plural': "3. Yo'nalishlar"},
        ),
    ]
