# Generated by Django 5.0.6 on 2024-07-01 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_alter_homecourses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecourses',
            options={'verbose_name': 'Kurslar', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AddField(
            model_name='homecourses',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/', verbose_name='Hover rasmi'),
        ),
        migrations.AddField(
            model_name='homecourses',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='courses_images/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
