# Generated by Django 5.0.6 on 2024-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_homecourses_hover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='leaders_images/', verbose_name='Rasm')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('facebook_url', models.URLField(default='#', verbose_name='Facebook Havolasi')),
                ('telegram_url', models.URLField(default='#', verbose_name='Telegram Havolasi')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbarlar',
            },
        ),
    ]
