# Generated by Django 5.0.6 on 2024-07-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_homeleader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecourses',
            options={'verbose_name': '3. Kurslar', 'verbose_name_plural': '3. Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='homeleader',
            options={'verbose_name': '4. Rahbarlar', 'verbose_name_plural': '4. Rahbarlar'},
        ),
        migrations.AlterModelOptions(
            name='hometitles',
            options={'verbose_name': 'Sarlavhalar', 'verbose_name_plural': 'Sarlavhalar'},
        ),
    ]
