# Generated by Django 5.0.6 on 2024-07-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_alter_homecourses_options_alter_homeleader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeleader',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ism familiya'),
        ),
    ]
