# Generated by Django 5.0.6 on 2024-07-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_alter_homeleader_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
            ],
            options={
                'verbose_name': '5. FAQlar',
                'verbose_name_plural': '5. FAQlar',
            },
        ),
        migrations.CreateModel(
            name='FaqTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=255, verbose_name='Kichik Sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='faq_titles/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': '5. FAQ Sarlavha',
                'verbose_name_plural': '5. FAQ Sarlavha',
            },
        ),
    ]
