# Generated by Django 5.0.6 on 2024-07-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_faq_faqtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Rasm')),
                ('link', models.URLField(verbose_name='Havola')),
            ],
            options={
                'verbose_name': '6. Hamkorlar',
                'verbose_name_plural': '6. Hamkorlar',
            },
        ),
    ]
