# Generated by Django 5.0.6 on 2024-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_title', models.CharField(max_length=255, verbose_name='Kichik Sarlavha')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('body', models.TextField(verbose_name='Tana Matni')),
                ('submit', models.BooleanField(default=False, verbose_name='Yuborish')),
                ('iframe', models.TextField(verbose_name='Iframe google xarita uchun')),
            ],
            options={
                'verbose_name': "6. Biz bilan bog'lanish",
                'verbose_name_plural': "6. Biz bilan bog'lanish",
            },
        ),
    ]
