# Generated by Django 5.0.6 on 2024-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='submit',
            field=models.BooleanField(default=False, verbose_name='Yuborish tugmasi'),
        ),
    ]
