# Generated by Django 5.0.6 on 2024-07-16 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_alter_contactus_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='bot_token',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Bot tokeni'),
            preserve_default=False,
        ),
    ]
