# Generated by Django 5.0.6 on 2024-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_contactus_body_en_contactus_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeleader',
            name='facebook_url',
            field=models.CharField(default='#', max_length=255, verbose_name='Facebook Havolasi'),
        ),
        migrations.AlterField(
            model_name='homeleader',
            name='telegram_url',
            field=models.CharField(default='#', max_length=255, verbose_name='Telegram Havolasi'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(max_length=255, verbose_name='Tugma Havolasi'),
        ),
    ]
