# Generated by Django 5.0.6 on 2024-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newsimage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='news_app.newsimage', verbose_name='Rasmlar'),
        ),
    ]
