# Generated by Django 5.0.6 on 2024-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_elon',
            field=models.BooleanField(default=False, verbose_name="E'lonmi?"),
        ),
    ]
