# Generated by Django 5.0.6 on 2024-06-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
