# Generated by Django 5.0.6 on 2024-07-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0002_page_content_en_page_content_ru_page_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file', models.FileField(upload_to='pages/files/', verbose_name='Faylni yuklang')),
            ],
            options={
                'verbose_name': 'Fayllar',
                'verbose_name_plural': 'Fayllar',
            },
        ),
    ]
