# Generated by Django 5.0.6 on 2024-07-21 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Menyu Turi',
                'verbose_name_plural': 'Menyu Turlari',
            },
        ),
        migrations.CreateModel(
            name='OneNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Havola')),
                ('is_submenu', models.BooleanField(default=False, verbose_name='Ichma-ich menyu')),
                ('nav_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi')),
            ],
            options={
                'verbose_name': '1-darajali menyu',
                'verbose_name_plural': '1-darajali menyular',
            },
        ),
        migrations.CreateModel(
            name='TwoNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Havola')),
                ('is_submenu', models.BooleanField(default=False, verbose_name='Ichma-ich menyu')),
                ('nav_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi')),
                ('one_navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_navbars', to='navbar_app.onenavbar', verbose_name='1-darajali menyu')),
            ],
            options={
                'verbose_name': '2-darajali menyu',
                'verbose_name_plural': '2-darajali menyular',
            },
        ),
        migrations.CreateModel(
            name='ThreeNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Havola')),
                ('is_submenu', models.BooleanField(default=False, verbose_name='Ichma-ich menyu')),
                ('nav_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi')),
                ('two_navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_navbars', to='navbar_app.twonavbar', verbose_name='2-darajali menyu')),
            ],
            options={
                'verbose_name': '3-darajali menyu',
                'verbose_name_plural': '3-darajali menyular',
            },
        ),
    ]
