# Generated by Django 5.0.6 on 2024-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onenavbar',
            options={'ordering': ['order'], 'verbose_name': '1-darajali menyu', 'verbose_name_plural': '1-darajali menyular'},
        ),
        migrations.AlterModelOptions(
            name='threenavbar',
            options={'ordering': ['order'], 'verbose_name': '3-darajali menyu', 'verbose_name_plural': '3-darajali menyular'},
        ),
        migrations.AlterModelOptions(
            name='twonavbar',
            options={'ordering': ['order'], 'verbose_name': '2-darajali menyu', 'verbose_name_plural': '2-darajali menyular'},
        ),
        migrations.AddField(
            model_name='onenavbar',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='threenavbar',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='twonavbar',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
    ]
