# Generated by Django 5.0.6 on 2024-07-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar_app', '0002_alter_onenavbar_options_alter_threenavbar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onenavbar',
            name='nav_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi'),
        ),
        migrations.AlterField(
            model_name='threenavbar',
            name='nav_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi'),
        ),
        migrations.AlterField(
            model_name='twonavbar',
            name='nav_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='two_navbars', to='navbar_app.navtype', verbose_name='Menyu Turi'),
        ),
    ]
