# Generated by Django 5.0.6 on 2024-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar_app', '0003_alter_onenavbar_nav_type_alter_threenavbar_nav_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navtype',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='navtype',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='navtype',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='onenavbar',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='onenavbar',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='onenavbar',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='threenavbar',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='threenavbar',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='threenavbar',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='twonavbar',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='twonavbar',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='twonavbar',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
    ]
