# Generated by Django 5.0.6 on 2024-07-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar_app', '0004_navtype_title_en_navtype_title_ru_navtype_title_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threenavbar',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='threenavbar',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='threenavbar',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='twonavbar',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='twonavbar',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='twonavbar',
            name='title_uz',
        ),
    ]
