# Generated by Django 5.0.6 on 2024-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('keywords', models.TextField(verbose_name="Kalit so'zlar")),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('author', models.CharField(max_length=255, verbose_name='Muallif')),
                ('favicon', models.ImageField(upload_to='favicons/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'SEO Sozlamalari',
                'verbose_name_plural': 'SEO Sozlamalari',
            },
        ),
    ]
