# Generated by Django 5.0.6 on 2024-06-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_link', models.URLField(max_length=255, verbose_name='Telefon havolasi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email_link', models.URLField(max_length=255, verbose_name='Email havolasi')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('bot_link', models.URLField(max_length=255, verbose_name='Bot havolasi')),
                ('bot', models.CharField(max_length=100, verbose_name='Bot')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo')),
                ('right_button_link', models.URLField(max_length=255, verbose_name="O'ng tugma havolasi")),
                ('right_button_title', models.CharField(max_length=50, verbose_name="O'ng tugma sarlavhasi")),
                ('search_placeholder', models.CharField(max_length=100, verbose_name='Qidiruv matni')),
            ],
            options={
                'verbose_name': 'Header Sozlamalari',
                'verbose_name_plural': 'Header Sozlamalari',
            },
        ),
    ]
