# Generated by Django 5.0.6 on 2024-06-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_headersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('location', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone_link', models.URLField(max_length=255, verbose_name='Telefon havolasi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email_link', models.URLField(max_length=255, verbose_name='Email havolasi')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Kontakt Ma'lumotlari",
                'verbose_name_plural': "Kontakt Ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='FooterLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
            ],
            options={
                'verbose_name': 'Footer Havola Kategoriyasi',
                'verbose_name_plural': 'Footer Havola Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(upload_to='footer_logos/', verbose_name='Footer logosi')),
                ('body', models.TextField(verbose_name='Matn')),
                ('copyright', models.CharField(max_length=255, verbose_name='Mualliflik huquqi')),
            ],
            options={
                'verbose_name': 'Footer Sozlamalari',
                'verbose_name_plural': 'Footer Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('link', models.URLField(max_length=255, verbose_name='Havola')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='settings_app.footerlinkcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Footer Havolasi',
                'verbose_name_plural': 'Footer Havolalari',
            },
        ),
    ]
