# Generated by Django 5.0.6 on 2024-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_contactinfo_footerlinkcategory_footersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('i_class', models.CharField(max_length=255, verbose_name='Ikonka klassi')),
                ('link', models.CharField(max_length=255, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq sozlamasi',
                'verbose_name_plural': 'Ijtimoiy tarmoq sozlamalari',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': "Kontakt Ma'lumoti", 'verbose_name_plural': "Kontakt Ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer Sozlamasi', 'verbose_name_plural': 'Footer Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Header Sozlamasi', 'verbose_name_plural': 'Header Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': 'SEO Sozlamasi', 'verbose_name_plural': 'SEO Sozlamalari'},
        ),
    ]
