# Generated by Django 5.0.6 on 2024-06-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_socialsettings_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email_link',
            field=models.CharField(max_length=255, verbose_name='Email havolasi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_link',
            field=models.CharField(max_length=255, verbose_name='Telefon havolasi'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='bot_link',
            field=models.CharField(max_length=255, verbose_name='Bot havolasi'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='email_link',
            field=models.CharField(max_length=255, verbose_name='Email havolasi'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='phone_link',
            field=models.CharField(max_length=255, verbose_name='Telefon havolasi'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='right_button_link',
            field=models.CharField(max_length=255, verbose_name="O'ng tugma havolasi"),
        ),
    ]
