# Generated by Django 5.0.6 on 2024-06-29 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_alter_contactinfo_email_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='logo_alt',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Logo alt'),
            preserve_default=False,
        ),
    ]
