# Generated by Django 5.0.6 on 2024-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_contactinfo_location_en_contactinfo_location_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=255, verbose_name='Bosh sahifa')),
            ],
            options={
                'verbose_name': '8. Ichki matnlar',
                'verbose_name_plural': '8. Ichki matnlar',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': "6. Kontakt Ma'lumoti", 'verbose_name_plural': "6. Kontakt Ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': '5. Footer Havolasi', 'verbose_name_plural': '5. Footer Havolalari'},
        ),
        migrations.AlterModelOptions(
            name='footerlinkcategory',
            options={'verbose_name': '4. Footer Havola Kategoriyasi', 'verbose_name_plural': '4. Footer Havola Kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': '3. Footer Sozlamasi', 'verbose_name_plural': '3. Footer Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': '2. Header Sozlamasi', 'verbose_name_plural': '2. Header Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': '1. SEO Sozlamasi', 'verbose_name_plural': '1. SEO Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='socialsettings',
            options={'verbose_name': '7. Ijtimoiy tarmoq sozlamasi', 'verbose_name_plural': '7. Ijtimoiy tarmoq sozlamalari'},
        ),
    ]
