# Generated by Django 5.0.6 on 2024-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_moretitles_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretitles',
            name='home_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Bosh sahifa'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='home_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Bosh sahifa'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='home_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Bosh sahifa'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='related_news',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'xshash yangiliklar"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='related_news_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'xshash yangiliklar"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='related_news_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'xshash yangiliklar"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='related_news_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'xshash yangiliklar"),
        ),
    ]
