# Generated by Django 5.0.6 on 2024-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_moretitles_home_en_moretitles_home_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretitles',
            name='news_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar sahifasi'),
        ),
    ]
