# Generated by Django 5.0.6 on 2024-07-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0010_moretitles_news_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretitles',
            name='news_page_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar sahifasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='news_page_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar sahifasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='news_page_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar sahifasi'),
        ),
    ]
