# Generated by Django 5.0.6 on 2024-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_moretitles_news_page_en_moretitles_news_page_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretitles',
            name='news_category_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar kategoriya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='news_category_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar kategoriya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='news_category_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar kategoriya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='news_category_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yangiliklar kategoriya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='search_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qidiruv sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='search_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qidiruv sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='search_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qidiruv sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='search_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qidiruv sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='social_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ijtimoiy tarmoqlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='social_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ijtimoiy tarmoqlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='social_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ijtimoiy tarmoqlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='social_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ijtimoiy tarmoqlar sarlavhasi'),
        ),
    ]
