# Generated by Django 5.0.6 on 2024-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0012_moretitles_news_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moretitles',
            name='empty_news',
            field=models.TextField(blank=True, null=True, verbose_name="Yangiliklar yo'q"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='empty_news_en',
            field=models.TextField(blank=True, null=True, verbose_name="Yangiliklar yo'q"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='empty_news_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Yangiliklar yo'q"),
        ),
        migrations.AddField(
            model_name='moretitles',
            name='empty_news_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Yangiliklar yo'q"),
        ),
    ]
