# Generated by Django 5.0.6 on 2024-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_moretitles_empty_news_moretitles_empty_news_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='robots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
