# Generated by Django 5.0.6 on 2024-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0014_seosettings_robots_seosettings_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_404_title', models.CharField(max_length=255, verbose_name='404 Sarlavhasi')),
                ('error_404_title_uz', models.CharField(max_length=255, null=True, verbose_name='404 Sarlavhasi')),
                ('error_404_title_ru', models.CharField(max_length=255, null=True, verbose_name='404 Sarlavhasi')),
                ('error_404_title_en', models.CharField(max_length=255, null=True, verbose_name='404 Sarlavhasi')),
                ('error_404_body', models.TextField(verbose_name='404 Matni')),
                ('error_404_body_uz', models.TextField(null=True, verbose_name='404 Matni')),
                ('error_404_body_ru', models.TextField(null=True, verbose_name='404 Matni')),
                ('error_404_body_en', models.TextField(null=True, verbose_name='404 Matni')),
                ('error_500_title', models.CharField(max_length=255, verbose_name='500 Sarlavhasi')),
                ('error_500_title_uz', models.CharField(max_length=255, null=True, verbose_name='500 Sarlavhasi')),
                ('error_500_title_ru', models.CharField(max_length=255, null=True, verbose_name='500 Sarlavhasi')),
                ('error_500_title_en', models.CharField(max_length=255, null=True, verbose_name='500 Sarlavhasi')),
                ('error_500_body', models.TextField(verbose_name='500 Matni')),
                ('error_500_body_uz', models.TextField(null=True, verbose_name='500 Matni')),
                ('error_500_body_ru', models.TextField(null=True, verbose_name='500 Matni')),
                ('error_500_body_en', models.TextField(null=True, verbose_name='500 Matni')),
            ],
        ),
    ]
