# Generated by Django 5.0.6 on 2024-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0015_errortexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bot nomi')),
                ('token', models.TextField(verbose_name='Token')),
            ],
            options={
                'verbose_name': '9. Telegram bot sozlamalari',
                'verbose_name_plural': '9. Telegram bot sozlamalari',
            },
        ),
        migrations.AlterModelOptions(
            name='errortexts',
            options={'verbose_name': '8. Xatolik sahifasi matnlari', 'verbose_name_plural': '8. Xatolik sahifasi matnlari'},
        ),
    ]
